config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Home page
  root to: 'home#index'
  get 'home/index'

  # Login routing
  devise_for :users

  # Item routes
  resources :items, except: [:index]
  post 'items/:id/save_expiries', to: 'items#save_expiries'

  # Location routes
  resources :locations
  get 'locations/:parent_id/new', to: 'locations#new', as: 'new_sublocation'
  get 'locations/:id/stock_take', to: 'stock_take#location', as: 'stock_take'
  get 'locations/:id/report', to: 'reports#location', as: 'location_report'

  resources :stock_items # Stock item route
  resources :users # User administration route
  get 'report', to: 'reports#location', as: 'report' # Global report route
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # No authorisation required
  skip_authorization_check

  # GET /
  def index
  end
end

app/views/home/index.html.erb
<h1>Stock Management System</h1>

<%# Generate links user has access to and display them on screen %>
<% links = [] %>
<% if can? :read, Location %>
  <% links.push(link_to 'Locations', locations_path, :class=>"btn-group linktobutton") %>
<% end %>

<% if can? :read, StockItem %>
  <% links.push(link_to 'Stock Items', stock_items_path,:class=>"btn-group linktobutton") %>
<% end %>

<% if can? :read, User %>
  <% links.push(link_to 'Users', users_path,:class=>"btn-group linktobutton") %>
<% end %>

<%== links.join(" ") %>