config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Home page
  root to: 'home#index'
  get 'home/index'

  # Login routing
  devise_for :users

  # Item routes
  resources :items, except: [:index]
  post 'items/:id/save_expiries', to: 'items#save_expiries'

  # Location routes
  resources :locations
  get 'locations/:parent_id/new', to: 'locations#new', as: 'new_sublocation'
  get 'locations/:id/stock_take', to: 'stock_take#location', as: 'stock_take'
  get 'locations/:id/report', to: 'reports#location', as: 'location_report'

  resources :stock_items # Stock item route
  resources :users # User administration route
  get 'report', to: 'reports#location', as: 'report' # Global report route
end

app/models/location.rb
class Location < ApplicationRecord
  # Associations
  has_many :items, dependent: :destroy
  has_many :stock_items, through: :items
  has_many :item_expiries, through: :items
  has_many :stock_item_summaries

  # Prevent ancestry from changing
  attr_readonly :ancestry

  # Auditing
  acts_as_paranoid
  audited

  # Validations
  validates :name, presence: true

  # Nested set
  has_ancestry orphan_strategy: :destroy

  # List
  acts_as_list scope: [:ancestry]

  # Get parent name
  def parent_name
    parent != nil ? parent.name : "No Parent"
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  load_and_authorize_resource # Authorise actions

  # Set location before actions
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  def index
    add_breadcrumb "Locations", :locations_path
    @locations_tree = Location.arrange(order: [:position, :name, :id])
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @locations_tree = @location.descendants.arrange(order: [:position, :name, :id])
    @items = @location.items.includes(:stock_item).preload(:item_summary).order("stock_items.name")
  end

  # GET /locations/new
  def new
    @location = Location.new
    if params[:parent_id]
      # Set location parent if parent id parameter and add breadcrumb
      @location.parent = Location.find(params[:parent_id])

      add_location_breadcrumb @location.parent
      add_breadcrumb "New", new_sublocation_path(params[:parent_id])
    else
      # Add breadcrumb for new root location
      add_breadcrumb "Locations", :locations_path
      add_breadcrumb "New", new_location_path
    end

    # Set default position to end
    @location.position = (Location.where(ancestry: @location.ancestry).maximum(:position) || 0) + 1
  end

  # GET /locations/1/edit
  def edit
    add_breadcrumb "Edit", edit_location_path(@location)
  end

  # POST /locations
  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location, notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to @location, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /locations/1
  def destroy
    if @location.parent == nil
      redirect_to locations_url, notice: 'Location was successfully destroyed.'
    else
      redirect_to location_path(@location.parent), notice: 'Location was successfully destroyed.'
    end
    @location.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
      add_location_breadcrumb @location
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:parent_id, :name, :position, :description)
    end
end

app/views/locations/_form.html.erb
<%= bootstrap_form_for(location) do |form| %>
  <%# Render errors %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# Render inputs for each attribute %>
  <div class="field">
    <%= form.text_field :parent_location_name, disabled: true, value: location.parent_name %>
  </div>

  <div class="field">
    <%= form.hidden_field :parent_id, id: :location_parent_id %>
  </div>

  <div class="field">
    <%= form.text_field :name, id: :location_name %>
  </div>

  <div class="field">
    <%= form.text_field :description, id: :location_description %>
  </div>

  <div class="field">
    <%= form.number_field :position, id: :location_position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/_report_form.html.erb
<%# Render report form if user has access to reports %>
<% if can? :location, :report %>
  <%# Set URLs based on location parameter %>
  <% if location.nil? %>
    <% url = report_path %>
    <% csv_url = report_path(format: "csv") %>
  <% else %>
    <% url = location_report_path(location) %>
    <% csv_url = location_report_path(location, format: "csv") %>
  <% end %>

  <h2>Report</h2>
  <%# Manual form as bootstrap forms gem does not support disabling hidden fields %>
  <%= bootstrap_form_tag url: url, method: :get do |f| %>
    <div class="checkbox">
      <label for="display_tree">
        <input type="checkbox" value="1" name="display_tree" id="display_tree"> Display Sub-Locations
      </label>
    </div>
    <div class="checkbox">
      <label for="order_to">
        <input type="checkbox" value="1" name="order_to" id="order_to"> Order Report
      </label>
    </div>
    <div class="checkbox">
      <label for="expiries">
        <input type="checkbox" value="1" name="expiries" id="expiries"> Display Expiry Dates (Only valid with Display Sub-Locations enabled)
      </label>
    </div>
    <input type="submit" value="View" class="btn btn-primary">
    <button  type="button" class="btn btn-secondary" onclick="location.href='<%=csv_url%>'">Download Order Summary</button>
  <% end %>
<% end %>
<br>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%# Render location form %>
<%= render 'form', location: @location %>

app/views/locations/index.html.erb
<%# Render location tree in body, cannot be done in head due to turbolinks %>
<%= javascript_tag do %>
  var tree = <%== render partial: "locations/tree", formats: [:json], object: @locations_tree, as: :locations_tree %>;
<% end %>

<h1>Locations</h1>
<%# Render report form %>
<%= render 'locations/report_form', location: nil %>

<%# Placeholder for tree %>
<div id="tree"></div>

<%# Render add location link if user has access to create location %>
<% if can? :create, Location %>
  <%= link_to 'New Location', new_location_path %>
<% end %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%# Render location form %>
<%= render 'form', location: @location %>

app/views/locations/show.html.erb
<%# Render location tree as javascript %>
<%# This must be in the body as otherwise turbolinks will prevent refreshing %>
<%= javascript_tag do %>
  var tree = <%== render partial: "locations/tree", formats: [:json], object: @locations_tree, as: :locations_tree %>;
<% end %>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<%# Add links that user has permission to access %>
<% links = [] %>
<% if can? :location, :stock_take %>
  <% links.push(link_to 'Stock Take', stock_take_path(@location)) %>
<% end %>

<% if can? :edit, @location %>
  <% links.push(link_to 'Edit', edit_location_path(@location)) %>
<% end %>

<% if can? :destroy, @location %>
  <% links.push(link_to 'Delete', @location, method: :delete, data: { confirm: 'Are you sure?' }) %>
<% end %>

<%# Display links %>
<%== links.join(' | ') %>

<%= render 'locations/report_form', location: @location %>

<%# Render a table containing all items which are present at location %>
<h2>Items</h2>
<%= render 'items/table', items: @items, name_type: :stock_item %>

<%# Add link to create new item if user has permission %>
<% if can? :create, Item %>
  <%= link_to 'Add Item', new_item_path(location_id: @location) %>
<% end %>

<h2>Sublocations</h2>
<%# Placeholder for bootstrap tree %>
<div id="tree"></div>

<%# Add link to create new location below current location %>
<% if can? :create, Location %>
  <%= link_to 'Add Sublocation', new_sublocation_path(parent_id: @location) %>
<% end %>